"""content_html 필드 추가

Revision ID: 2af67a824ad1
Revises: 937634546512
Create Date: 2017-09-11 23:01:14.701074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af67a824ad1'
down_revision = '937634546512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###
