"""user 이메일 검증확인필드 추가

Revision ID: 383a04627073
Revises: 82842ca25399
Create Date: 2017-08-31 21:43:31.657315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383a04627073'
down_revision = '82842ca25399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
