"""필드 추가

Revision ID: 937634546512
Revises: ef1e23cf781a
Create Date: 2017-09-10 22:31:12.857575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937634546512'
down_revision = 'ef1e23cf781a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
